[package]
name = "git2_credentials"
version = "0.1.1"
authors = ["David Bernard <david.bernard.31@gmail.com>"]
edition = "2018"
description = "Provide credential function to used with git2::RemoteCallbacks.credentials"
readme = "README.md"
license = "Apache-2.0"
keywords = ["git"]
repository = "https://github.com/davidB/git2_credentials"
homepage = "https://github.com/davidB/git2_credentials"
exclude = ["/azure-pipelines.yml", "/docs/**", "/scripts", ".gitignore", "/tests/**"]

[dependencies]
git2 = "0.8"
failure = "0.1.5"
dialoguer = "0.3.0"

[dev-dependencies]
tempfile = "3.0.7"
